### ISSUE TITLE
rename modid.mixins.json

### ISSUE THREAD

**Issue by milkev** [HughBone/scaffold-forever#3]
leaving the mixin config as this value can cause crashes with other mods that do the same. modid should be replaced with your mod id.

**Comment by kalinzange** [comment]
Can Confirm
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods infinitelava and scaffoldforever
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by milkev** [comment]
this issue is still present on newest versions of this mod. its a simple rename or removal of the file if its not in use. please fix this.
